version: 0.2

phases:
  build:
    commands:
      # install tox
      - pip install tox tox-conda

      # install brew for tbb dependency
      - curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh > /tmp/install.sh
      - cat /tmp/install.sh
      - chmod +x /tmp/install.sh
      - useradd -m brewuser
      - echo "brewuser:brewuser" | chpasswd 
      - adduser brewuser sudo
      - /bin/su -c /tmp/install.sh - brewuser
      - /bin/su -c '/home/brewuser/.linuxbrew/bin/brew install tbb' - brewuser
      - PATH=/home/brewuser/.linuxbrew/bin:$PATH

      # run linters, format verification, and package checks
      - start_time=`date +%s`
      - tox -e flake8,pylint,black-check,twine
      - ./ci/scripts/displaytime.sh 'flake8,pylint,twine,black-check' $start_time

      # run unit tests
      - start_time=`date +%s`
      - tox -e py37
      - ./ci/scripts/displaytime.sh 'py37 unit' $start_time