version: 0.2

phases:
  build:
    commands:
      # install tbb dependency
      - apt update -y
      - apt-get install -y libtbb-dev

      # install tox
      - pip install tox tox-conda==0.7.3

      # run linters, format verification, and package checks
      - start_time=`date +%s`
      - tox -e flake8,pylint,black-check,twine
      - ./ci/scripts/displaytime.sh 'flake8,pylint,twine,black-check' $start_time

      # run unit tests
      - start_time=`date +%s`
      - tox -e py37
      - ./ci/scripts/displaytime.sh 'py37 unit' $start_time

      # run unit tests for contrib
      - start_time=`date +%s`
      - tox -e contrib_taei_py37
      - ./ci/scripts/displaytime.sh 'contrib_taei_py37 unit' $start_time