version: 0.2

phases:
  build:
    commands:
      # run git-secrets
      - git-secrets --scan-history

      # install tox
      - pip install tox tox-conda

      # prepare release
      - git-release --prepare --min-version 1.0.0

      # run linters
      - tox -e flake8,pylint

      # run format verification
      - tox -e black-check

      # run package check
      - tox -e twine

      # run unit tests
      - tox -e py37

      # generate distribution package
      - python3 setup.py sdist

      # publish release to github
      - git-release --publish --min-version 1.0.0

artifacts:
  files:
    - dist/sagemaker-scikit-learn-extension-*.tar.gz
  name: ARTIFACT_1
  discard-paths: yes