version: 0.2

phases:

      

  build:
    commands:
      - apt install libtbb-dev

      # install tox
      - pip install tox tox-conda

      # run linters, format verification, and package checks
      - start_time=`date +%s`
      - tox -e flake8,pylint,black-check,twine
      - ./ci/scripts/displaytime.sh 'flake8,pylint,twine,black-check' $start_time

      # run unit tests
      - start_time=`date +%s`
      - tox -e py37
      - ./ci/scripts/displaytime.sh 'py37 unit' $start_time